# Generated by Django 5.1.15 on 2026-04-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, default='', help_text="The raw natural language input from the user. Example: 'Design a 3-floor house on a 30×40 plot in Mumbai.' Phase 2: This will be parsed by Ollama into parsed_input.")),
                ('parsed_input', models.JSONField(blank=True, help_text='Structured version of the user input (dict). In Phase 1: populated from the API request body directly. In Phase 2: populated by the Ollama NLP parser from raw_text. Schema: {region, building_type, plot_width_m, plot_depth_m, num_floors, num_units, rooms, preferences, plot_facing_direction}', null=True)),
                ('region', models.CharField(default='default', help_text="Region ID used for bylaw lookup. Examples: 'india_mumbai', 'india_delhi', 'usa_nyc', 'default' Matches a file in backend/bylaws/{region}.json", max_length=100)),
                ('building_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', help_text='Type of building. Determines which bylaw rules apply.', max_length=50)),
                ('plot_width_m', models.FloatField(default=0.0, help_text='Width of the plot in metres (the dimension along the road).')),
                ('plot_depth_m', models.FloatField(default=0.0, help_text='Depth of the plot in metres (perpendicular to the road).')),
                ('num_floors', models.IntegerField(default=2, help_text='Number of floors requested by the user (including ground floor).')),
                ('num_units', models.IntegerField(default=1, help_text='Number of residential units. 1 = single house. 2+ = apartment building. Used for parking calculation.')),
                ('plot_facing_direction', models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('northeast', 'North-East'), ('northwest', 'North-West'), ('southeast', 'South-East'), ('southwest', 'South-West')], default='north', help_text='The direction the main entrance of the plot faces. Used by the Vastu Shastra engine (Phase 2) for room placement.', max_length=20)),
                ('compliance_report', models.JSONField(blank=True, help_text="The output of the deterministic rule engine. Stores setback calculations, FAR checks, floor limits, parking requirements. Schema matches ComplianceReport.to_dict(). Set after status='compliance_checked'.", null=True)),
                ('applied_bylaws', models.JSONField(blank=True, help_text='The full bylaw ruleset that was loaded and applied. Useful for auditing: tells you exactly which rules were used. Schema matches BylawRuleset.to_dict().', null=True)),
                ('vastu_report', models.JSONField(blank=True, help_text='Vastu Shastra compliance report (added in Phase 2). Advisory output — not a blocking compliance check. Schema: {score, room_checks: [{room, direction, vastu_recommended, passed, note}]} ', null=True)),
                ('retrieved_knowledge', models.JSONField(blank=True, help_text='Top-K knowledge chunks retrieved from BM25 RAG (added in Phase 2). These are the architectural principles used to guide layout decisions. Schema: [{id, text, source, score}]', null=True)),
                ('layout_zones', models.JSONField(blank=True, help_text='List of spatial zones generated by the layout generator (Phase 3). Schema: [{room_type, x, y, floor, width_m, depth_m, direction}]', null=True)),
                ('explanation', models.TextField(blank=True, default='', help_text="Human-readable explanation generated by the system (Phase 3). Combines bylaw decisions, RAG-retrieved knowledge, and Vastu notes. Example: 'Kitchen placed in south-east as per Vastu guidelines.'")),
                ('glb_file_path', models.CharField(blank=True, default='', help_text='Relative path to the generated GLB 3D model file (Phase 3). Served at MEDIA_URL/outputs/<filename>.glb Load in model-viewer or Blender for 3D preview.', max_length=500)),
                ('hypar_json_path', models.CharField(blank=True, default='', help_text='Relative path to the Hypar-compatible element JSON file (Phase 3). Drag this file to hypar.io to view the building model in the Hypar viewer.', max_length=500)),
                ('status', models.CharField(choices=[('received', 'Received'), ('compliance_checked', 'Compliance Checked'), ('layout_generated', 'Layout Generated'), ('model_generated', 'Model Generated'), ('completed', 'Completed'), ('failed', 'Failed')], default='received', help_text='Current processing status of this design session.', max_length=30)),
                ('error_message', models.TextField(blank=True, default='', help_text="If status='failed', this field contains the error message. Useful for debugging API failures.")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this session was first created (set automatically).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update (set automatically on each save).')),
            ],
            options={
                'verbose_name': 'Design Session',
                'verbose_name_plural': 'Design Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
